"""Explicit policy-lineage fork; retain the league, not the previous learner."""
import copy
import time
import torch

def prepare_checkpoint(checkpoint, bundle):
    if checkpoint['model'].keys()!=bundle['model'].keys():
        raise ValueError('model schema mismatch')
    for key,value in bundle['model'].items():
        if value.shape!=checkpoint['model'][key].shape or not torch.isfinite(value).all():
            raise ValueError('invalid warm-start weights')
    out=copy.deepcopy(checkpoint)
    out['model']=copy.deepcopy(bundle['model'])
    out['norm']=copy.deepcopy(bundle['norm'])
    for key in ('actor_opt','critic_opt'): out[key]['state']={}
    out['vnext_probe']={}
    for key in ('exploiter_init_first','exploiter_init_rest'):
        out[key]={'model':copy.deepcopy(bundle['model']),'norm':copy.deepcopy(bundle['norm'])}
    for entry in out['pool']:
        entry.update(ema=.5,past_best=.5,games=0.)
    for record in out['league_archive']['records']:
        record.update(current_score=.5,past_best=.5,regression=0.,online_ema_score=None,
                      online_games=0.,clean_paired_score=None,current_score_source='warm_start_unmeasured')
    out['warm_start_transition']={'status':'pending','schedule_iteration':out['iteration'],
        'previous_main_global_step':out['global_step'],'provenance':copy.deepcopy(bundle.get('provenance',{})),
        'optimizer_reset':True,'online_scores_reset':True}
    out['global_step']=int(bundle['provenance']['source_global_step'])
    return out

def finish_pending(trainer,save_path):
    transition=getattr(trainer,'warm_start_transition',None)
    if not transition or transition.get('status')!='pending': return False
    if not trainer.checkpoint_safe or trainer.actor_opt.state or trainer.critic_opt.state:
        raise RuntimeError('warm start requires committed boundary and fresh optimizer')
    adapter=trainer.vnext_milestone_adapter
    controller=adapter.controller
    if not controller.may_mutate_training: raise RuntimeError('league is frozen')
    started=time.perf_counter()
    active=trainer.pool.active_entries()
    strategic=[int(e['archive_id']) for e in active if e['role'] in ('core','challenger')]
    challengers=[int(e['archive_id']) for e in active if e['role']=='challenger']
    current=trainer._archive_current('milestone_main',metrics={'warm_start_source':transition['provenance']})
    selected=[current,*strategic]
    if len(selected)>20 or len(selected)!=len(set(selected)): raise RuntimeError('invalid warm-start solver')
    # Existing opponent-vs-opponent evidence still describes unchanged policies.
    # The newly archived Main receives a fresh row; do not reuse old Main scores.
    queries=adapter._complete_active_solver_game(trainer,policy_ids=selected,
        iteration=trainer.iteration,current_id=current,candidate_ids=set())
    p=controller.config.payoff_graph
    solution=controller.graph.conservative_nash(selected,minimum_blocks=p.solver_paired_blocks,
        evaluator_protocol=p.evaluator_protocol,scenario_bank_versions=p.solver_compatible_scenario_banks)
    trainer.pool.replace_latest(trainer.model,trainer.norm,trainer.iteration)
    trainer._latest_clone_iteration=trainer.iteration
    trainer._last_milestone_archive_id=current
    controller.last_solver_ids=selected
    controller.last_index['solver_eligible_ids']=selected
    adapter.refresh_roster(trainer,iteration=trainer.iteration,current_id=current,
        forced_challenger_ids=challengers,selected_ids=selected,nash_override=solution)
    for identity,record in trainer.archive.records.items(): record['nash_mass']=float(solution.get(identity,0.))
    adapter.sync_membership_metadata(trainer,solver_ids=selected,nash_override=solution)
    trainer._refresh_weights()
    # Discard episodes collected with another Main; all subsequent returns are
    # generated by the new policy. This is an intentional lineage transition.
    trainer._reset_env_state()
    trainer._refresh_weights()
    controller.archive_index.rebuild(trainer.archive.state_dict(),controller.graph,iteration=trainer.iteration)
    controller.budget.add('evaluation',time.perf_counter()-started)
    transition.update(status='complete',new_main_archive_id=current,solver_ids=selected,payoff_queries=len(queries))
    controller.log.append('main_warm_start_completed',dict(transition),iteration=trainer.iteration)
    trainer.vnext_control_state=controller.state_dict()
    trainer.save(save_path)
    controller.persist()
    print(f'[warm-start] complete: main={current} schedule_iteration={trainer.iteration} queries={len(queries)}',flush=True)
    return True
