#pragma once

#include "../../behaviortree_cpp_v3/action_node.h"
#include "../../behaviortree_cpp_v3/bt_factory.h"
#include "../BlackBoard/CPPBlackBoard.h"

using namespace BT;

namespace Action
{
	enum CompetitionConditionKind
	{
		COND_GROUND_DANGER, COND_DEFENSIVE, COND_UNDER_FIRE, COND_PREDICTED_THREAT,
		COND_OFFENSIVE, COND_IN_MY_WEZ, COND_OVERSHOOT, COND_FAR_BEHIND,
		COND_ENDGAME_DENY, COND_FAR_NEUTRAL, COND_PRE_MERGE, COND_POST_MERGE,
		COND_ENERGY_ADVANTAGE, COND_STALEMATE, COND_CONTROL_ZONE,
		COND_MAINTAIN_MANEUVER, COND_THREAT_CLEARED, COND_ROOM_TO_MANEUVER,
		COND_OUTSIDE_TURN_CIRCLE, COND_LOW_ENERGY, COND_CROSSING_CONE_LEAD,
		COND_NEAR_CONE_AIM, COND_PENDING_SCISSORS, COND_SHOT_COMMIT,
		COND_HABFM_BRIDGE, COND_CONTROL_ZONE_CAPTURE,
		COND_ENEMY_PURE_THREAT, COND_NODE35_ACTIVE,
		COND_ENEMY_LEAD_THREAT, COND_ENEMY_LAG_PURSUIT, COND_DEFENSIVE_COUNTER_CUE
	};

	enum CompetitionTaskKind
	{
		TASK_CLIMB_RECOVER, TASK_BREAK_JINK, TASK_HARD_TURN, TASK_TRACK,
		TASK_HIGH_YOYO, TASK_LEAD_INTERCEPT, TASK_LAG_ENTRY, TASK_EXTEND,
		TASK_MERGE_OFFSET, TASK_TWO_CIRCLE, TASK_ONE_CIRCLE, TASK_SCISSORS,
		TASK_PURE_PURSUIT, TASK_CONTROL_ZONE, TASK_MAINTAIN_MANEUVER,
		TASK_ENERGY_RECOVER, TASK_FOLLOW_HOSTILE, TASK_CONE_LEAD_TRACK,
		TASK_PULL_TO_HUD, TASK_ARC_REJOIN, TASK_NODE35_EXTENDED_SIX
	};

	class CompetitionNode : public SyncActionNode
	{
	public:
		CompetitionNode(const std::string& name, const NodeConfiguration& config);
		static PortsList providedPorts();
	protected:
		CPPBlackBoard* board();
		double number(const char* name, double fallback);
	};

#define DECLARE_SIMPLE_NODE(Name) \
	class Name : public CompetitionNode { public: using CompetitionNode::CompetitionNode; NodeStatus tick() override; };
	DECLARE_SIMPLE_NODE(UpdateGeometry)
	DECLARE_SIMPLE_NODE(UpdateEnergy)
	DECLARE_SIMPLE_NODE(UpdateEnemyTurnCircle)
	DECLARE_SIMPLE_NODE(UpdatePhase)
	DECLARE_SIMPLE_NODE(UpdateDamageScore)
	DECLARE_SIMPLE_NODE(ComputeThrottle)
	DECLARE_SIMPLE_NODE(BaselineCorePolicy)
#undef DECLARE_SIMPLE_NODE

	class CompetitionCondition : public CompetitionNode
	{
	public:
		CompetitionCondition(const std::string& name, const NodeConfiguration& config, CompetitionConditionKind kind);
		NodeStatus tick() override;
	private:
		CompetitionConditionKind kind_;
	};

	class CompetitionTask : public CompetitionNode
	{
	public:
		CompetitionTask(const std::string& name, const NodeConfiguration& config, CompetitionTaskKind kind);
		NodeStatus tick() override;
	private:
		CompetitionTaskKind kind_;
	};

#define DECLARE_CONDITION_NODE(Name, Kind) \
	class Name : public CompetitionCondition { public: Name(const std::string& n, const NodeConfiguration& c) : CompetitionCondition(n, c, Kind) {} };
	DECLARE_CONDITION_NODE(DECO_GroundDanger, COND_GROUND_DANGER)
	DECLARE_CONDITION_NODE(DECO_Defensive, COND_DEFENSIVE)
	DECLARE_CONDITION_NODE(DECO_UnderFire, COND_UNDER_FIRE)
	DECLARE_CONDITION_NODE(DECO_PredictedThreat, COND_PREDICTED_THREAT)
	DECLARE_CONDITION_NODE(DECO_Offensive, COND_OFFENSIVE)
	DECLARE_CONDITION_NODE(DECO_InMyWEZ, COND_IN_MY_WEZ)
	DECLARE_CONDITION_NODE(DECO_Overshoot, COND_OVERSHOOT)
	DECLARE_CONDITION_NODE(DECO_FarBehind, COND_FAR_BEHIND)
	DECLARE_CONDITION_NODE(DECO_EndgameDeny, COND_ENDGAME_DENY)
	DECLARE_CONDITION_NODE(DECO_FarNeutral, COND_FAR_NEUTRAL)
	DECLARE_CONDITION_NODE(DECO_PreMerge, COND_PRE_MERGE)
	DECLARE_CONDITION_NODE(DECO_PostMerge, COND_POST_MERGE)
	DECLARE_CONDITION_NODE(DECO_EnergyAdvantage, COND_ENERGY_ADVANTAGE)
	DECLARE_CONDITION_NODE(DECO_Stalemate, COND_STALEMATE)
	DECLARE_CONDITION_NODE(DECO_ControlZone, COND_CONTROL_ZONE)
	DECLARE_CONDITION_NODE(DECO_MaintainManeuver, COND_MAINTAIN_MANEUVER)
	DECLARE_CONDITION_NODE(DECO_ThreatCleared, COND_THREAT_CLEARED)
	DECLARE_CONDITION_NODE(DECO_RoomToManeuver, COND_ROOM_TO_MANEUVER)
	DECLARE_CONDITION_NODE(DECO_OutsideTurnCircle, COND_OUTSIDE_TURN_CIRCLE)
	DECLARE_CONDITION_NODE(DECO_LowEnergy, COND_LOW_ENERGY)
	DECLARE_CONDITION_NODE(DECO_CrossingConeLead, COND_CROSSING_CONE_LEAD)
	DECLARE_CONDITION_NODE(DECO_NearConeAim, COND_NEAR_CONE_AIM)
	DECLARE_CONDITION_NODE(DECO_PendingScissors, COND_PENDING_SCISSORS)
	DECLARE_CONDITION_NODE(DECO_ShotCommit, COND_SHOT_COMMIT)
	DECLARE_CONDITION_NODE(DECO_HABFMBridge, COND_HABFM_BRIDGE)
	DECLARE_CONDITION_NODE(DECO_ControlZoneCapture, COND_CONTROL_ZONE_CAPTURE)
	DECLARE_CONDITION_NODE(DECO_EnemyPureThreat, COND_ENEMY_PURE_THREAT)
	DECLARE_CONDITION_NODE(DECO_Node35Active, COND_NODE35_ACTIVE)
	DECLARE_CONDITION_NODE(DECO_EnemyLeadThreat, COND_ENEMY_LEAD_THREAT)
	DECLARE_CONDITION_NODE(DECO_EnemyLagPursuit, COND_ENEMY_LAG_PURSUIT)
	DECLARE_CONDITION_NODE(DECO_DefensiveCounterCue, COND_DEFENSIVE_COUNTER_CUE)
#undef DECLARE_CONDITION_NODE

#define DECLARE_TASK_NODE(Name, Kind) \
	class Name : public CompetitionTask { public: Name(const std::string& n, const NodeConfiguration& c) : CompetitionTask(n, c, Kind) {} };
	DECLARE_TASK_NODE(Task_ClimbRecover, TASK_CLIMB_RECOVER)
	DECLARE_TASK_NODE(Task_BreakJink, TASK_BREAK_JINK)
	DECLARE_TASK_NODE(Task_HardTurn, TASK_HARD_TURN)
	DECLARE_TASK_NODE(Task_Track, TASK_TRACK)
	DECLARE_TASK_NODE(Task_HighYoYo, TASK_HIGH_YOYO)
	DECLARE_TASK_NODE(Task_LeadIntercept, TASK_LEAD_INTERCEPT)
	DECLARE_TASK_NODE(Task_LagEntry, TASK_LAG_ENTRY)
	DECLARE_TASK_NODE(Task_Extend, TASK_EXTEND)
	DECLARE_TASK_NODE(Task_MergeOffset, TASK_MERGE_OFFSET)
	DECLARE_TASK_NODE(Task_TwoCircle, TASK_TWO_CIRCLE)
	DECLARE_TASK_NODE(Task_OneCircle, TASK_ONE_CIRCLE)
	DECLARE_TASK_NODE(Task_Scissors, TASK_SCISSORS)
	DECLARE_TASK_NODE(Task_PurePursuit, TASK_PURE_PURSUIT)
	DECLARE_TASK_NODE(Task_ControlZone, TASK_CONTROL_ZONE)
	DECLARE_TASK_NODE(Task_MaintainManeuver, TASK_MAINTAIN_MANEUVER)
	DECLARE_TASK_NODE(Task_EnergyRecover, TASK_ENERGY_RECOVER)
	DECLARE_TASK_NODE(Task_FollowHostile, TASK_FOLLOW_HOSTILE)
	DECLARE_TASK_NODE(Task_ConeLeadTrack, TASK_CONE_LEAD_TRACK)
	DECLARE_TASK_NODE(Task_PullToHUD, TASK_PULL_TO_HUD)
	DECLARE_TASK_NODE(Task_ArcRejoin, TASK_ARC_REJOIN)
	DECLARE_TASK_NODE(Task_Node35ExtendedSixLag, TASK_NODE35_EXTENDED_SIX)
#undef DECLARE_TASK_NODE

	void RegisterCompetitionNodes(BehaviorTreeFactory& factory);
}
